backend:
  name: github
  repo: "lakeevesham/lakeevesham.github.io"
  branch: main
  open_authoring: true
publish_mode: editorial_workflow
media_folder: 'img'
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_posts/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: layout, widget: hidden, default: post }
      - { name: title }
      - { name: categories, required: false }
      - { name: body, widget: markdown }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home page'
        name: 'index'
        file: 'index.markdown'
        fields:
          - { name: list_title }
          - name: upcoming_events
            widget: list
            fields:
              - { name: name }
              - { name: date }
              - { name: url, required: false }
          - { name: body, widget: markdown }
      - label: 'About page'
        name: 'about'
        file: 'about.markdown'
        fields:
          - { name: title }
          - { name: permalink }
          - { name: body, widget: markdown }
      - label: 'Newsletters page'
        name: 'newsletters'
        file: 'newsletters.markdown'
        fields:
          - { name: title }
          - { name: permalink }
          - { name: body, widget: markdown }
      - label: 'Garden page'
        name: 'garden'
        file: 'garden.markdown'
        fields:
          - { name: title }
          - { name: permalink }
          - { name: body, widget: markdown }
